// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = { aws_appsync_graphqlEndpoint: 'https://murl5sdvjffqdastco4lptkyda.appsync-api.us-east-1.amazonaws.com/graphql',
aws_appsync_region: 'us-east-1',
aws_appsync_authenticationType: 'API_KEY', // or 'AMAZON_COGNITO_USER_POOLS', 'AWS_IAM', etc.
aws_appsync_apiKey: 'da2-e62odg4hqvbfjjxk3tnawbbyhu', // API Key if you're using API_KEY authentication
}

export default awsmobile;